name: wremotely_clickhouse
version: "1.0.0"
config-version: 2
profile: wremotely_clickhouse
macro-paths: [macros]
model-paths: [models]
seed-paths: [seeds]
clean-targets: [target, dbt_packages]

models:
  wremotely_clickhouse:
    staging:
      +materialized: table
    intermediate:
      +materialized: table
    marts:
      +materialized: table
